### ISSUE TITLE
Kind.Unterhaltseinnahmen

### ISSUE THREAD

**Issue by paleise** [europace/baufismart-kundenangaben-api#100]
Hallo
es fehlt die Möglichkeit bei Kind das Feld Unterhaltseinnahmen auf Nein zu stellen.
Gruß Peter

**Comment by MikeKrueger75** [comment]
Hallo Peter, 

danke für dein Feedback. Wir haben die Anforderung in Issue #115 auch von anderen Partnern bekommen. 
Deshalb schließe ich dieses Issue.
