### ISSUE TITLE
 OAuth2-Client Scopes

### ISSUE THREAD

**Issue by steegc** [europace/baufismart-kundenangaben-api#101]
Hallo,

ich bin mal wieder auf die Angaben zu den Scopes reingefallen.

Ich versuche den ApiClients immer nur die Scopes zu geben, die explizit aufgelistet sind (+impersonieren) weil ich mit eine übergeordneten Plakette arbeite.
Leider führt das auch hier wieder zu einem Forbidden.

Habe mich damit an den support gewendet. Danach ist mir selbst eingefallen, dass es das schonmal gab. Jetzt gebe ich beim Token erzeugen einfach alle Scopes mit und schon funktioniert es.

Gruß

**Comment by MikeKrueger75** [comment]
Hallo Carl, 

für die Verwendung der Kundenangaben-API ist der Scope `baufinanzierung:vorgang:anlegen` Voraussetzung.
Es ist nicht erforderlich alle Scopes zuverwenden.

Viele Grüße, 
Mike
