### ISSUE TITLE
zusatzangeben_kunde_ing geburtsland

### ISSUE THREAD

**Issue by paleise** [europace/baufismart-kundenangaben-api#104]
mach ich bei der Übertragung des Geburtslands etwas falsch? Bekomme hier Fehler "muss ein valider ISO... Code sein".

"zusatzangaben": {
							"zusatzangabenProProduktanbieter": [
								{
									"berufsgruppe": "ANGESTELLTER",
									"privateKrankenversicherungMonatlicheAusgaben": 123.0,
									"weitereStaatsangehoerigkeitenErfassung": {
										"@type": "KEINE_WEITERE_STAATSANGEHOERIGKEITEN"
									},
									"geburtsland": "EE",
									"@type": "ZUSATZANGABEN_KUNDE_ING"
								}

**Comment by paleise** [comment]
Hallo, jetzt klappt's....

**Comment by ElisaBaum** [comment]
Hallo @paleise, 
ich würde das Issue schließen, da du geschrieben hast, dass jetzt alles klappt.
