### ISSUE TITLE
Fehlermeldung bei unbekannten Properties zurückgeben (war vormals: Persondendaten werden nicht übertragen)

### ISSUE THREAD

**Issue by ic-hv** [europace/baufismart-kundenangaben-api#105]
Ich musste - leider jetzt erst nach LIVE-Gang - feststellen, das die Personendaten wohl zwar sauber zu euch übetragen werden, diese aber nicht in dem Vorgang landen, alle anderen Daten sind da, aber die Personendaten fehlen:

![daten](https://user-images.githubusercontent.com/26538616/123068163-ec5d4480-d411-11eb-9137-f329d4cc5964.png)
![daten2](https://user-images.githubusercontent.com/26538616/123068172-eebf9e80-d411-11eb-9cde-01c7094ac586.png)

Bitte ASAP lösen!

**Comment by ElisaBaum** [comment]
Hallo,

da scheint sich ein Fehler bei den Daten eingeschlichen zu haben. Das Property heißt `personendaten` anstatt `persondendaten`. Mit dieser Korrektur sollten die Personendaten auch im Vorgang landen.

**Comment by ic-hv** [comment]
Ah ok, jetzt seh' ich es. Danke!

Könnte man die API aber vielleicht dahingehend anpassen, das sie bei unbekannten Properties eine Fehlermedlung zurückgibt? So weit ich mich erinnere hat die BEX-API das noch gemacht.

Weil es wäre schon schön gut, wenn man frühzeitig mitkriegen würde, das man da irgendwo nen Typo/ Fehler drin hat, bevor die Daten dann einfachstillschweigened verlorengehen ...
Aber wäre es nicht möglich das die API-Schnittstelle das nicht checkt und Propertes

**Comment by ElisaBaum** [comment]
Hallo ic-hv,

die API wurde möglichst fehlertolerant designed. Es ist also beabsichtigt, dass unbekannte Properties zu keinem Fehler führen. Eine ausführlichere Begründung findest du [hier](https://github.com/europace/baufismart-kundenangaben-api#was-passiert-mit-falschen-datenfeldern).

Zur Validierung der Anfragedaten steht der Endpunkt `/kundenangaben/body-validation` zur Verfügung. Mit diesem können solche Fehler entdeckt werden.

**Comment by ic-hv** [comment]
Hallo Elisa,

leider fängt der Endpunkt `/kundenangaben/body-validation` derartige Tippfehler auch nicht ab. Der Request wird anstandslos akzeptiert. Wäre schön wenn man wenigstens durch Nutzung dieses Endpunkts auf unbekannte Properties hingewiesen werden würde ... ist das machbar?

**Comment by ic-hv** [comment]
Hintergrund ist das die Kunden-Applikation Fälle aus dem kundenseitigen CRM via Kundenangaben-API zu Europace hochlädt und allerdings im späteren Verlauf sich via Vorgänge -API auch wieder die Änderungen am Vorgang von Europace ins CRM zurücksynct (downloaded). Wenn jetzt ein Information im CRM vorhanden ist,  aber evtl. von der Kundenangaben-API (wg. Tippfehler) verworfen wird und wir davon nichts mitkriegen, dann verschwindet diese Information endgültig auch aus dem Kunden-CRM bei nächsten Download des Vorgangs via Vorgaänge-API ...

**Comment by nar-ep** [comment]
Hi ic-hv,

vielen Dank für das Feedback zur Kundenangaben-API. Wir haben deinen Feature Wunsch aufgenommen. Das Feature liegt nun in unserem Backlog und wird entsprechend der Priorisierung bearbeitet.
