### ISSUE TITLE
KfW / BEG

### ISSUE THREAD

**Issue by paleise** [europace/baufismart-kundenangaben-api#106]
Könnt ihr schon ein Ausblick geben, wann die neuen nötigen Felder für die neuen KfW Produkte eingebaut werden?
Bereits Danke für eure Mühe!

Gruß 
Peter Artelt

**Comment by ElisaBaum** [comment]
Hallo @paleise,

die neuen KFW-Programme werden seit Version [1.3.1](https://github.com/europace/baufismart-kundenangaben-api/releases/tag/1.3.1) unterstützt.
