### ISSUE TITLE
English please

### ISSUE THREAD

**Issue by oleander** [europace/baufismart-kundenangaben-api#109]
Hi,

Would it be possible to use English instead of german for the OpenAPI specification? A team at my current company is working on migrating from your legacy API to this and the german code is driving our engineers nuts; even the native german speaking ones.

Any input on the subject is valuable.

Thanks.

**Comment by nar-ep** [comment]
Hi oleander,

at the moment we're not planning to release an english version of our API specs. 

Kind regards

**Comment by timurso** [comment]
Guys, this is the most counterintuitive decision that you could have made. You decided to have an open API, that means you have made a strategic decision to allow for external parties to integrate and build on top of your know-how. But having the API written in German goes against that strategy, that way you are making other engineers' work MUCH harder and ultimately alienating them. 
That's almost the attitude of "well they want something from us, so they will figure it out". Why did you bother with documentation then? :)
