### ISSUE TITLE
Postman Beispiel zum Kundenangaben aktualisieren resultiert in einem 400 Bad Request - "Cannot deserialize into 'bearbeiter'" - Feld 'bearbeiter' existiert laut Dokumentation nicht im Objekt 'UpdateKundenangabenRequest' 

### ISSUE THREAD

**Issue by anderha** [europace/baufismart-kundenangaben-api#111]
Hallo zusammen,

Mit dem [Commit von gestern](https://github.com/europace/baufismart-kundenangaben-api/commit/aa85ed9a14574428174ee9a4c661071b0c833e4f) soll es möglich sein einen Kundenvorgang zu aktualisieren. Der Request ist auch bereits in der zur Verfügung gestellten Postman Collection hinterlegt. Führe ich diesen aus erhalte ich allerdings einen 400 Bad Request.    

Genauer:
```json
{
    "type": "https://api.europace.de/kundenangaben/problem/bad-request",
    "title": "Bad Request",
    "status": 400,
    "detail": "Cannot deserialize into 'bearbeiter' at line: 1, column: 223",
    "traceId": "EP-API-POSTMAN-COLLECTION-5761"
}
```

Die Dokumentation verrät mir nun folgendes:   
Das Feld "bearbeiter" gehört zum Objekt "Betreuung", welches wiederum in "ImportMetadaten" vorkommt. Das wiederum wird nur in "ImportKundenangabenRequest" verwendet. Für den PUT Request soll aber laut API Dokumentation das Objekt "UpdateKundenangabenRequest" verwendet werden, welches keines der zuvor genannten Objekte/Felder enthält.    

Handelt es sich hierbei um einen Bug oder einen Fehler meinerseits?   

Hier ein Screenshot vom Request in Postman. Die Vorgangsnummer habe ich in den Umgebungsvariablen hinterlegt. Den Body habe ich nicht verändert, er ist eins zu eins der Beispielbody in der zur Verfügung gestellten Postman Collection.   

![grafik](https://user-images.githubusercontent.com/36031262/123774697-f5e12380-d8cd-11eb-88fe-b226b1118494.png)

**Comment by ElisaBaum** [comment]
Hallo @anderha,

ich vermute, dass der Vorgang keinen Bearbeiter hat. Das ist eine Voraussetzung für das erfolgreiche Aktualisieren der Kundenangaben (siehe Voraussetzung unter [Vorgang überschreiben](https://github.com/europace/baufismart-kundenangaben-api#beispiel-vorgang-%C3%BCberschreiben)). 
Kannst du das bitte mal überprüfen?

**Comment by anderha** [comment]
Hallo @mgords, ich bin dazu der falsche Ansprechpartner, da ich nicht bei Europace arbeite. Bitte einen neuen Issue aufmachen oder jemanden von Europace markieren
