### ISSUE TITLE
GetrenntLebend als Familienstand wird als nicht valide eingestuft

### ISSUE THREAD

**Issue by D0mc3k** [europace/baufismart-kundenangaben-api#116]
Hallo Europace Team,

beim Familienstand funktionieren alle @Type Varianten außer für "GetrenntLebend". Ich habe folgende @Type Varianten ausprobiert und bekomme jdes Mal vom body-validation Endpoint einen Fehler geliefert:

- GETRENNTLEBEND
- GetrenntLebend
- GETRENNT

    "type": "https://api.europace.de/kundenangaben/problem/bad-request",
    "title": "Bad Request",
    "status": 400,
    "detail": "Cannot deserialize into kundenangaben.haushalte.[0].kunden.[0].personendaten.familienstand: @type contains unknown type id 'GETRENNTLEBEND'",

    "type": "https://api.europace.de/kundenangaben/problem/bad-request",
    "title": "Bad Request",
    "status": 400,
    "detail": "Cannot deserialize into kundenangaben.haushalte.[0].kunden.[0].personendaten.familienstand: @type contains unknown type id 'GetrenntLebend'",

Viele Grüße
Domcek

**Comment by roamingthings** [comment]
Hallo Domcek,

der `@type` für die getrennt Lebend lautet `GETRENNT_LEBEND`.
Generell wird bei den Typen `CAMEL_CASE` verwendet.

Grüße,
Alexander

**Comment by D0mc3k** [comment]
Vielen Dank @roamingthings
