### ISSUE TITLE
Beschaeftigung @type HaushaltendePerson nicht valide

### ISSUE THREAD

**Issue by D0mc3k** [europace/baufismart-kundenangaben-api#117]
Hallo Europace Team,

bei der Beschäftigung funktionieren alle @type Varianten außer "HaushaltendePerson". Ich habe es auch mit "Hausfrau" und "Hausmann" getestet. Dazu alle Varianten in UPPERCASE übergeben. Ich bekomme aber stets einen Bad Request vom body-validation Endpoint wenn ich eine der Angaben mache. Wie ist der korrekte aType?

Viele Grüße
Domcek

**Comment by roamingthings** [comment]
Hallo Domcek,

der `@type` für die haushaltende Person lautet `HAUSHALTENDE_PERSON`. Generell wird bei den Typen `CAMEL_CASE` verwendet.

Grüße,
Alexander

**Comment by D0mc3k** [comment]
Vielen Dank @roamingthings
