### ISSUE TITLE
ISO 3166-1 alpha-2 Code "XK" - Kosovo

### ISSUE THREAD

**Issue by steegc** [europace/baufismart-kundenangaben-api#119]
Hello,

I tryed "XK" as ISO 3166-1 alpha-2 Code for Kosovo (submitted as country of birth), which should be the right code.

As result I got a "bad request".

Switching the country of birth to for example "DE" fixed it.

Is "XK" unknown in the  API?

**Comment by FabianStuehler** [comment]
Hello,

XK is now known for the API.
