### ISSUE TITLE
Update eines Vorgangs per beliebigen hierarchisch höherstehenden "Caller"

### ISSUE THREAD

**Issue by ic-hv** [europace/baufismart-kundenangaben-api#139]
Ware es möglich die Einschränkung "caller is editor of the case"  beim Updating eines Vorgangs dahingehend aufzuweichen, das der Caller in der Partnermanagment-Hierarchie über dem Bearbeiter stehen muss, um den Vorgang einer hierarchisch tieferstehenden Peroson updaten zu können?

Hintergrund ist: In der Regel **erstellen** wir Vorgänge für beliebige (hierarchisch tieferstehende) Bearbeiter via Kundengaben API mit **einem** API-Client, der bei **einer** Plakette hinterlegt ist, die hierarchisch über allen beteiligten Bearbeitern steht und das klappt dann auch wunderbar.

Wenn wir nun aber einen Vorgang **updaten** wollen, dann müssten wir quasi bei **jedem** Mitarbeiter einen API-CLient anlegen, um dessen Vorgänge updaten zu können. Was spricht denn dagegen, den Update-Fall genauso wie den Create-Fall zu handhaben?

Herzliche Grüße,
Heiko Vogel

**Comment by dneukirchen** [comment]
+1

**Comment by martinklewitz** [comment]
Hallo
 
Für dieses Szenario haben wir den OAuth2 Impersonierung Workflow entwickelt.
Mit diesem Flow kann ein zentraler Client einen Nutzer Token ausstellen für einen Nutzer auf den der zentrale Client Zugriff hat. Mit diesem Token können nun Operationen ausgeführt werden im Namen des Nutzers.
Dafür müssen die Vorgänge dann nicht übergeben werden.
 
Hier findest Du mehr dazu [Client-impersonation](https://docs.api.europace.de/common/authentifizierung/client-credential-flow/#how-to-authenticate-different-users-with-one-client-impersonation)
 
Mit freundlichen Grüßen
Martin Klewitz

**Comment by ic-hv** [comment]
Ahhh, ok cool mit dem Scope: **baufinanzierung:vorgang:schreiben impersonieren** klappt das tatsächlich. Danke!
