### ISSUE TITLE
Entity ids

### ISSUE THREAD

**Issue by dneukirchen** [europace/baufismart-kundenangaben-api#164]
To make mapping easier it would be nice to include entity ids in nested objects (should be the same ids that are already returned by the vorgänge api). 

* antragssteller
* kinder
* gebaeude
* bankverbindung
* bausparvertraege
* bestehendeDarlehen
* darlehensgeber
* lebensUndRentenVersicherungen
* ...

see https://europace.github.io/baufismart-vorgaenge-api/docs/index.html#get-/v2/vorgaenge/-vorgangsNummer-

**Comment by win36** [comment]
This would be especially useful for objects in arrays that are currently only addressable using their index which can easily change.

**Comment by win36** [comment]
This is going to solve some serious data synchronization issues for us. Thanks a lot!
