### ISSUE TITLE
KfwProgramm297 und KfwProgramm298 werden ignoriert

### ISSUE THREAD

**Issue by ic-hv** [europace/baufismart-kundenangaben-api#171]
Werden Finanzierungsbausteine für die KfwProgramme 297 bzw. 298 übermittelt, werden diese ignoriert. 
![kfw-ignored](https://github.com/europace/baufismart-kundenangaben-api/assets/26538616/5becd34a-0155-424c-a638-413677885316)

Anderweitige KfwProgramme werden nicht ignoriert und sind nach erfolgtem API-Request auch in der Web-Ansicht des Vorgangs auffindbar.

**Comment by the-real-andreasbk** [comment]
Aloha @ic-hv ,
danke für das Melden des Issues. 
In deinem Beispiel fehlte die Angabe des `kfwEnergieEffizienzStandard`. Die KfW 297, 298 ( und das neue 300 ) **bedingen**, dass entweder `KLIMAFREUNDLICH_STANDARD` oder `KLIMAFREUNDLICH_QNG` mitgeliefert wird.

Dies wäre z.B. eine mögliche Belegung der Ausprägung für das KfW 298 Programm:
```json
...
{
  "@type": "KFW_DARLEHEN",
  "darlehensbetrag": 135791.2,
  "kfwEndfaellig": "ENDFAELLIG_BERECHNET",
  "tilgungswunsch": {
    "@type": "RATE",
    "rate": 876.2,
    "tilgungsbeginn": "2023-10-15"
  },
  "programm": {
    "@type": "KFW_PROGRAMM_298",
    "kfwEnergieEffizienzStandard": "KLIMAFREUNDLICH_QNG",
    "laufzeitInJahren": 35,
    "zinsbindungInJahren": 10,
    "tilgungsfreieAnlaufjahre": 5
  }
}
...
```
Wir haben gerade eine neue Version der API released, die das Problem addressiert, dass dies bisher nicht durch die Doku ersichtlich war. 
https://github.com/europace/baufismart-kundenangaben-api/releases/tag/v1.4.25
