### ISSUE TITLE
Unterhaltseinnahmen & Kinderzulage für Riester wird nicht ausgelesen

### ISSUE THREAD

**Issue by D0mc3k** [europace/baufismart-kundenangaben-api#201]
Hallo Europace Team,

uns ist aufgefallen, dass bei Vorgängen mit festgelegten Werten für Unterhaltseinnahmen und Kinderzulage für Riester, die Werte nicht über die API im Objekt zurückgeliefert werden.
Es geht um folgende Felder
![image](https://github.com/europace/baufismart-kundenangaben-api/assets/4028192/b1f29ab1-cdc2-498f-8f1d-e4590776677c)

Viele Grüße

**Comment by fgellhorn** [comment]
Hallo Domcek,

danke für deine Mitteilung! Ich habe mir das angeschaut und kann deine Feststellung nicht bestätigen.

Wenn eine Auswahl bzw. Eingaben in BaufiSmart gemacht wurden, werden diese auch über die API ausgeliefert:
![Bildschirmfoto 2024-06-13 um 11 44 19](https://github.com/europace/baufismart-kundenangaben-api/assets/30745012/a4ef82a9-5f70-4562-9694-ef0072e0fc32)
![Bildschirmfoto 2024-06-13 um 11 44 33](https://github.com/europace/baufismart-kundenangaben-api/assets/30745012/b350c15f-090d-48e3-8f69-1d25b8ec11a5)


Ebenso werden die Daten beim Einspielen über die API in einen BaufiSmart Vorgang übernommen:
![Bildschirmfoto 2024-06-13 um 11 51 04](https://github.com/europace/baufismart-kundenangaben-api/assets/30745012/6f585fae-6a3c-4d08-aaf6-f7efe6d6faec)
![Bildschirmfoto 2024-06-13 um 11 51 26](https://github.com/europace/baufismart-kundenangaben-api/assets/30745012/7ed35ccc-d871-46b4-8af0-49645d535590)

Bitte prüfe deine erfassten Daten nochmals.
Bei weiteren Rückfragen stehen wir dir gern zu Verfügung.

Viele Grüße
Frank
