### ISSUE TITLE
Which API Operations are supported?

### ISSUE THREAD

**Issue by MariosoDinsoso** [europace/baufismart-kundenangaben-api#36]
We need the possibility to update an existing Case in Baufismart.
What Endpoints (POST/PUT/PATCH) would be available?
Thanks in advance!

**Comment by acodingsquirrel** [comment]
Hey,
in der ersten Umsetzung gibt es noch nicht die Möglichkeit Vorgänge zu editieren.
Wir sehen viele sinnvolle Anwendungsfälle für das Editieren von Vorgängen. Editieren von Vorgängen ermöglicht externe Systeme (wie CRM-Systeme) mit BaufiSmart zu synchronisieren. Editieren von Vorgängen ermöglich das Verbraucher und Berater parallel an einem Vorgang arbeiten können.
Wir finden das Thema wichtig und haben eine Umsetzung angedacht. Über den konkreten Zeitplan der Umsetzung auf unserer Seite können wir momentan noch keine Aussage treffen. 
Kannst du uns noch etwas genauer erzählen, wieso du Vorgänge verändern möchtest? Welche Aktion führt dazu, das eine Veränderung per API vorgenommen werden soll? Kannst du evtl. sagen welche Felder im Detail editiert werden sollen und warum?
Vielen Danke. Wir würden deinen Anwendungsfall gerne bei der Umsetzung berücksichtigen.

**Comment by MariosoDinsoso** [comment]
Hallo, unsere Kunden füllen in unserem Kundenportal eine Selbstauskunft aus und wir möchten, dass die Angaben der Selbstauskunft in den Vorgang in Europace übernommen werden. Keine große Sache.

Wir möchten updaten:
- Antragsteller
- Haushalt
- Kinder
- Objektdaten
- Finanzbedarf
Am sinnvollsten wäre sogar, nicht den ganzen Vorgang zu updaten, sondern nur die einzelnen Objekte.

Unsere Berater müssten sonst bis zu 138 Felder per Hand Copy und Pasten, um die Kundenangaben aus der digitalen Selbstauskunft in den Vorgang zu übergeben und das ist alles andere als smart ;-)

Viele Grüße

**Comment by acodingsquirrel** [comment]
Hallo Mario,

wir wollen deinen Anwendungsfall perspektivisch unterstützen.
Im ersten Schritt setzen wir um, das ein Vorgang mit den mitgegebenen Daten angelegt wird.

In Folgeschritten werden wir unterstützen, das Datenfelder für deinen Anwendungsfall editiert werden können. 
Danke, das du deinen Anwendungsfall genau beschrieben hast.

**Comment by roamingthings** [comment]
Ich schließe dieses Issue, da es keine weitere Beiträge gegeben hat.
