### ISSUE TITLE
Wohnfläche einer Eigentumswohnung

### ISSUE THREAD

**Issue by tilomlr** [europace/baufismart-kundenangaben-api#63]
Hallo Europace-Team,

könntet ihr uns helfen? Wir fragen uns, wo man bei einer [Eigentumswohnung](https://htmlpreview.github.io/?https://github.com/europace/baufismart-kundenangaben-api/blob/v1.0.4/reference/index.html#_Eigentumswohnung) die Wohnfläche angibt?

VG Tilo

**Comment by s-gurevich** [comment]
Hi,

gebaeude -> nutzung -> wohnen -> gesamtflaeche 

https://htmlpreview.github.io/?https://github.com/europace/baufismart-kundenangaben-api/blob/v1.0.4/reference/index.html#_Flaechennutzung

**Comment by s-gurevich** [comment]
```
"typ": {
  "@type": "EIGENTUMSWOHNUNG",
  "grundstuecksgroesse": 1000,
  "gebaeude": {
    "baujahr": 2020,
    "bauweise": "GLAS_STAHL",
    "anzahlGeschosse": 5,
    "zustand": "MITTEL",
    "ausstattung": "MITTEL",
    "nutzung": {
      "wohnen": {
        "gesamtflaeche": 200,
        "nutzungsart": {
          "@type": "EIGENGENUTZT"
        }
      }
    }
  },
  "miteigentumsanteil": {
    "anteil": 100,
    "gesamt": 1000
  },
  "anzahlDerWohneinheitenImObjekt": 10,
  "anzahlDerGewerbeeinheitenImObjekt": 0,
  "bezeichnungWohneinheit": "eOMtThyhVNLWUZN"
},
```

**Comment by tilomlr** [comment]
Hi @s-gurevich ,

vielen Dank für die schnelle Antwort.

VG Tilo
