### ISSUE TITLE
Service momentan nicht erreichbar?

### ISSUE THREAD

**Issue by paleise** [europace/baufismart-kundenangaben-api#65]
Hallo, erhalte momentan ein 503 Fehler.

**Comment by s-gurevich** [comment]
Hallo,

danke für die Nachfrage. Der Service ist verfügbar. Wir untersuchen das Problem und melden uns, wenn es behoben ist.

**Comment by paleise** [comment]
Ich habe jetzt noch weiter getestet. Mein Problem liegt beim Finanzierungszweck. Im Anhang eine Anfrage mit dem FinZweck "KAUF", und die gleiche Anfrage nur mit dem FinZweck "ANSCHLUSSFINANZIERUNG". Kauf geht nicht, Anschlussfin geht. Was mache ich falsch?
 
Vor allem erwarte ich bei Kauf keinen 503 Fehler.
 
Als Verbesserungsvorschlag für die Doku (HTML). Beim Finanzierungszweck gibt es ja nur das Feld "@type". Bei solchen Typen wäre es schön, wenn dabei stehen würde, welche Typen denn möglich sind, also hier Anschlussfinanzierung, Kauf, KaufNeubauVomBauträger... Weil z.B. bei FlexibelKurzfristigHandlungsfaehig gibt es auch scheinbar verschiedene Objekt die im Feld "@type" übergaben werden können, nur welche...
[kundenanfrage.zip](https://github.com/europace/baufismart-kundenangaben-api/files/5988911/kundenanfrage.zip)

**Comment by s-gurevich** [comment]
Jetzt solltest du auch den Kauf-Request erfolgreich absetzen lassen können.

Danke für dein Feedback zu der Doku. Momentan siehst du die Liste der möglichen Typen bei der Verwendung des Elterntyps:

![image](https://user-images.githubusercontent.com/47738739/108086169-60f43100-7076-11eb-95a5-c43a749c7ebc.png)

**Comment by paleise** [comment]
Leider bekomme ich bei einem Kauf immer noch eine 503 zurück. Habe das Beispiel aus meiner letzten Kommentar getestet.

**Comment by s-gurevich** [comment]
Könntest du nochmal probieren, bitte?

**Comment by paleise** [comment]
Ja, jetzt passt's. Danke!
