### ISSUE TITLE
HTML Doku types

### ISSUE THREAD

**Issue by paleise** [europace/baufismart-kundenangaben-api#66]
Hallo,
ich habe im letzten Issue schon darauf hingewiesen, dass die Types nicht durchgängig dokumentiert sind. Schaut mal bitte z.B. bei FLAECHENNUTZUNG.NUTZUNGSART. Ist vom Typ NUTZUNGSART, aber es steht nicht, was da rein muss/soll/kann.
Das fehlt bei einigen Feldern. Bei einigen ist das aber gut angegeben, wie z.B. bei sondertilgung. Oder verstehe ich da was falsch?
Danke bereits für eure Mühe

**Comment by paleise** [comment]
Hallo,
und wie ist das beim Feld ZusatzangabenImmobilieIng. Feld beleihungsobjekt ist vom Typ IngBeleihungsobjekt welches aber dann wieder nur das Feld type hat... Es gibt dann wohl wieder IngEingetumswohnung... aber wie muss das jetzt genau zusammengebaut werden?

**Comment by paleise** [comment]
Noch eine Anmerkung zu der HTML Doku:
BestehendesBauspardarlehen.darlehensgeber: ist das ein String? in der Klasse steht wohl darlehensgeber, aber ist nicht auf darlehensgeber verlinkt und die Klasse Darlehensgeber hat nur @type, wo kommt da jetzt der darlehensgeber text rein?

**Comment by acodingsquirrel** [comment]
Hallo palaise,
Danke für deinen Hinweis.
Wir haben uns deine Meldung im Team angeschaut. Du sprichst zurecht an, dass bei Feldern mit Wahlmöglichkeiten manchmal die möglichen Ausprägungen nicht aufgeführt werden.
Wir erzeugen das HTML als Referenzdokumentation, um bei der Umsetzung zu unterstützen. Das HTML erzeugen wir aus der yaml. Die Übersetzung anzupassen ist aufwendig und wir planen nicht, das von dir gemeldete Verhalten, zeitnah anzupassen.
Wir können dir jedoch sagen, wie du die möglichen Ausprägungen eines Feldes herausfinden kannst.
Wenn du an einer Stelle die möglichen Ausprägungen eines Feldes nicht findest, dann kannst du in der yaml nachschauen.
Diese findest du hier: https://github.com/europace/baufismart-kundenangaben-api/blob/master/kundenangaben-openapi.yaml
Wenn du zu dem gesuchten Feld springst, kannst du dann die gesuchte Ausprägungen entnehmen.

**Comment by paleise** [comment]
ok, vielen Dank.

**Comment by s-gurevich** [comment]
Hallo, wir haben bei diversen möglichen Ausprägungen von einem Typ, die Möglichkeiten in Textform aufgeführt.
