### ISSUE TITLE
Annuitaetendetail.Tilgungswunsch Volltilger

### ISSUE THREAD

**Issue by paleise** [europace/baufismart-kundenangaben-api#67]
Hallo, in der yaml bei Tilgungswunsch steht als Description "Darf nicht Volltilger enthalten", beim Mapping ist aber Volltilger angegeben.

**Comment by s-gurevich** [comment]
Hallo,

vielen Dank für den Hinweis. 

Diese Beschreibung gehört ausschließlich zum Tilgungswunsch-Feld im Variablen Darlehen. Da bei einem Variablen Darlehen der Zins änderbar ist, kann dort beim Tilgungswunsch kein Volltilger ausgewählt werden. In anderen Fällen ist der Volltilger eine valide Auswahl.

Wir werden das korrigieren.

**Comment by paleise** [comment]
Ok, danke für die Klärung.

**Comment by s-gurevich** [comment]
Hallo, wir haben diese und einige weiteren Stellen in der Dokumentation angepasst und bei diversen möglichen Ausprägungen von einem Typ, die Möglichkeiten in Textform aufgeführt.
