### ISSUE TITLE
BausparvertragAlsVermoegen.verwendung KeinEinsaz

### ISSUE THREAD

**Issue by paleise** [europace/baufismart-kundenangaben-api#70]
Hallo,
wenn der Bausparvertrag nicht zum Einsatz kommen soll, lässt man dann BausparvertragAlsVermoegen.verwendung weg? In Europace Web gibt es die Auswahl "gar nicht". Gleich bei den bestehenden Versicherungen.
Danke bereits für eure Mühe!

**Comment by s-gurevich** [comment]
Hallo,

danke für deine Frage.

Wir werden die Option für die UI-Auswahl "gar nicht" in der API ergänzen. Bis dahin lasse bitte die Verwendung leer, wenn das Vermögen nicht eingesetzt werden soll. 

Wir werden hier Bescheid sagen, wenn die Ergänzung online ist.

**Comment by s-gurevich** [comment]
Hallo Peter,

ab jetzt kannst du auch aktiv KeineVerwendung (UI = "gar nicht") über die API setzen. Das betrifft alle liquidierbaren (z.B. Sparpläne) und abtretbaren (z.B. Bausparverträge) Vermögenswerte.

**Comment by paleise** [comment]
Super! Danke für die Info! Werde das gleich am Montag einbauen.
Schönes Wochenende!
Gruß Peter
