### ISSUE TITLE
Anschlussfinanzierung, Darlehen des Finanzierungsobjekts Ablösen ja/nein

### ISSUE THREAD

**Issue by paleise** [europace/baufismart-kundenangaben-api#71]
Hallo,
bei Anschlussfinanzierungen fehlt mir das Feld "Ablösen ja/nein" in AbloesungBestehendsDarlehen. Oder gebe ich nur die Darlehen dort an, welche ich auch ablösen will? Im Web ist es so, dass ALLE Darlehen aufgeführt werden und die Auswahl Ablösen Ja/Nein getroffen werden kann.
Bereits vielen Dank für eure Mühe!
BTW: bin ich hier überhaupt richtig mit meinen Fragen, kann natürlich auch eine E-Mail an den Helpcenter in Europace schreiben, jedoch ist die Antwort hier super schnell...
Gruß Peter

**Comment by s-gurevich** [comment]
Hallo Peter,

in der Liste `abloesungDarlehenDesFinanzierungsobjektes` sollen nur `AbloesungBestehendesDarlehen` für Darlehen erfasst werden, die auch wirklich abgelöst werden sollen. In diesem Objekt stellst du die Beziehung zwischen dem abzulösenden Darlehen und dem Finanzierungsbaustein, welches das Darlehen ablösen soll, her. 

Inhaltliche Fragen, die die Nutzung der API betreffen, kannst du gern hier stellen.

Gruß,
Serafima

**Comment by paleise** [comment]
Hallo Serafima,
danke für den Hinweis. Ich habe das jetzt getestet. Ja es passt so, jedoch fehlt aus meiner Sicht die Möglichkeit, zu einem Darlehen welches nicht abgelöst wird, einen Wert für "Tritt im Rang zurück" einzutragen. Oder übersehe ich da etwas?
Vielen Dank bereits für deine Mühe!

Mit freundlichen Grüßen
INTERCAPITAL GMBH
Peter Artelt
E-Mail: Peter.Artelt@intercapital.de

**Comment by acodingsquirrel** [comment]
Hallo Peter,

Vielen Dank, dass du uns viel Feedback zur Kundenangaben-API gegeben hast.
Basierend auf deinem Feedback und Rückfragen haben wir eine größerer Änderung vorgenommen.

Bei Angaben, bei denen eine „ja/nein“-Auswahl weitere Felder sichtbar geschaltet hat, haben wir jetzt bei allen Stellen die Option eingeführt „ja“ und „nein“ zu übermitteln.

Damit kannst du auch die von dir gewünschten Daten übertragen.
Vielen Dank für deinen Input.

**Comment by paleise** [comment]
Hallo zusammen,
ich prüfe gerade das ja/nein Problem. Bei der Anschlussfinanzierung ist das etwas anders. Beispiel: auf dem Objekt lasten zwei Darlehen. Eins soll abgelöst werden, dass andere tritt im Rang zurück. Diese Eingabemöglichkeit habe ich in der WebUI, jedoch nicht in der Schnittstelle.
Ich mach das so: die beiden Darlehen sind unter finanzierungsobjekt.darlehnsliste eingetragen. Unter finanzierungsbedarf.finanzierungszweck.abloeungDarlehenDesFinanzierungsobjektes trage ich nur die Referenz zu dem Darlehen ein, welches abgelöst werden soll. In der WebUI erscheinen dann beide Darlehen unter Vorhaben/Darlehen des Finanzierungsobjekts. So weit gut, jedoch bei dem welches nicht abgelöst werden soll ist im Feld "Ablösen?" nichts ausgewählt, also weder ja noch nein. Ich sehe keine Möglichkeit über die Schnittstelle die korrekten Werte "nein" und dann im aufgehenden Feld "Tritt im Rang zurück" "ja" einzutragen.
