### ISSUE TITLE
Types Uppercase

### ISSUE THREAD

**Issue by paleise** [europace/baufismart-kundenangaben-api#72]
Hallo,
leider ist es scheinbar notwendig die Werte in den Feldern "@type" groß zu schreiben. Also z.B. ein "@type": "Verheiratet" funktioniert nicht, es ist "@type": "VERHEIRATET" nötig. Naja nicht wirklich ein Problem, aber evtl. könnte man das dokumentieren.
Gruß Peter

**Comment by s-gurevich** [comment]
Hallo Peter,

die `@type` Angabe wird im Screaming Snake Case geschrieben abgeleitet vom Typnamen.

Die Information findet sich in der OpenApi YAML-Datei unter `mapping`:

![image](https://user-images.githubusercontent.com/47738739/109160768-83710300-7776-11eb-8b43-2c614c11d576.png)

In der daraus generierten HTML-Ansicht fehlt die Info tatsächlich. Wir kümmern uns darum, die Doku in der HTML-Version zu ergänzen.

Gruß,
Serafima

**Comment by paleise** [comment]
Danke für die Klärung

**Comment by s-gurevich** [comment]
Hi Peter,

wir haben in der HTML Referenz einen Hinweis hinzugefügt:
https://htmlpreview.github.io/?https://github.com/europace/baufismart-kundenangaben-api/blob/master/reference/index.html#_definitions
