### ISSUE TITLE
Vermoegen.summeBankUndSparguthaben.Verwendung

### ISSUE THREAD

**Issue by paleise** [europace/baufismart-kundenangaben-api#73]
Hallo,
bitte entschuldigt, nochmals ich, auch wenn ich evtl. nerve...
unter finanzielleSitutation.vermoegen.summeBankUndSparguthaben.verwendung muss scheinbar der type mit Unterstrichen angegeben werden, also angenommen wird AUFLOESUNG_ALS_VERWENDUNG aber das ist nicht so in der Doku, dort ohne Unterstriche.
Gruß Peter

**Comment by paleise** [comment]
Scheinbar gibt es das bei einigen Feldern. Z.B.
						"tilgungswunsch": {
							"tilgungssatzInProzent": 2.0,
							"tilgungsbeginn": "2021-03-01",
							"@type": "TILGUNGINPROZENT"
						},
geht nicht, funktionieren tut TILGUNG_IN_PROZENT.
Wie kann ich denn das erkennen...
Danke für eure Mühe!
Peter

**Comment by s-gurevich** [comment]
Siehe Antwort in https://github.com/europace/baufismart-kundenangaben-api/issues/72

**Comment by paleise** [comment]
Hallo, danke für die Antwort. In #72 ist das so, aber nicht hier. In der yaml findet sich TILGUNG_IN_PROZENT nicht...
Gruß Peter

**Comment by s-gurevich** [comment]
Schaue mal hier:

![image](https://user-images.githubusercontent.com/47738739/109162018-03e43380-7778-11eb-9d32-233735156d2a.png)

**Comment by paleise** [comment]
Danke für die Klärung. Ok, muss weg von der html...
Danke für die Mühe.
LG Peter
