### ISSUE TITLE
Werte der Antwort

### ISSUE THREAD

**Issue by paleise** [europace/baufismart-kundenangaben-api#74]
In der Antwort erhält man momentan nur die Vorgangsnummer zurück. In der Bex hatte man noch mehr Angaben wie die WebUrl zurückbekommen. Ist das angedacht?
Peter

**Comment by roamingthings** [comment]
Hallo Peter,

bei der Neugestaltung der Kundenangaben-API haben wir diese URL weggelassen. Die Vorgangsnummer kann in den anderen APIs der Plattform verwendet werden.
Es ist nicht angedacht, eine Url aufzunehmen.

Grüße,
Alex

**Comment by paleise** [comment]
Ok, danke für die Klärung.
