### ISSUE TITLE
Setzen Gewerbefläche nicht vorhanden

### ISSUE THREAD

**Issue by paleise** [europace/baufismart-kundenangaben-api#75]
Hallo,
wie setze ich "Gewerbefläche vorhanden" auf nein. Lasse ich in der json Nutzung.Gewerbe weg ist nichts angekreuzt.
Danke für die Mühe!
Gruß Peter

**Comment by acodingsquirrel** [comment]
Hallo Peter,
wir können die Anfrage nachvollziehen. Momentan kann man Gewerbeflächen nicht auf "nein" setzten.
Wir prüfen das Anliegen jetzt intern und nehmen gegebenenfalls Anpassungen vor.

**Comment by acodingsquirrel** [comment]
Hallo Peter,

Vielen Dank, dass du uns viel Feedback zur Kundenangaben-API gegeben hast.
Basierend auf deinem Feedback und Rückfragen haben wir eine größerer Änderung vorgenommen.

Bei Angaben, bei denen eine „ja/nein“-Auswahl weitere Felder sichtbar geschaltet hat, haben wir jetzt bei allen Stellen die Option eingeführt „ja“ und „nein“ zu übermitteln.

Damit kannst du auch die von dir gewünschten Daten übertragen.
Vielen Dank für deinen Input.
