### ISSUE TITLE
Nebenkosten

### ISSUE THREAD

**Issue by paleise** [europace/baufismart-kundenangaben-api#77]
kurz vor dem Wochenende...
Übertrage ein Kauf, unten der Finanzierungszweck. Die Grunderwerbsteuer und der Kaufpreis werden korrekt übertragen. Bei den Notargebühren erhalte ich nach Übertrag 2% und ein Eurowert von 10.380.

			"finanzierungszweck": {
				"nebenKosten": {
					"notargebuehr": {
						"wert": 7735.0,
						"einheit": "EURO"
					},
					"grunderwerbsteuer": {
						"wert": 18165.0,
						"einheit": "EURO"
					}
				},
				"kaufpreis": 519000.0,
				"@type": "KAUF"
			},

**Comment by s-gurevich** [comment]
Könntest du versuchen, `nebenkosten` komplett klein zu schreiben? Bezeichner, die falsch geschrieben sind und optional sind, werden ignoriert. Bei einigen Nebenkostenangaben greifen dann Defaultwerte fürs Bundesland.

**Comment by paleise** [comment]
ok, das habe ich übersehen... teste ich, gehe davon aus dass das dann funktioniert
Danke!
