### ISSUE TITLE
Kobinationsdarlehen

### ISSUE THREAD

**Issue by paleise** [europace/baufismart-kundenangaben-api#78]
Hallo,
wie stelle ich ein Kombinationsdarlehen in den Finanzierungsbausteinen dar? Bei den möglichen Typen in Finanzierungsbausteine  gibt es dieses nicht. Mach ich ein Annuitätendarlehen mit Tilgungsaussetzung?

**Comment by s-gurevich** [comment]
Hallo,

Kombinationsdarlehen in der UI sind nur ein UI Goody zur einfacheren Erfassung. Wenn du unter `finanzierungsbausteine` mehrere Bausteine übergibst, die dem entsprechenden Usecase entsprechen, werden sie automatisch als Kombinationsdarlehen in der UI angezeigt.
Falls du jedoch ein Annuitätendarlehen tilgungsausgesetzt durch einen Bausparvertrag erfassen möchtest, so setzst du den Bausparbaustein im `tilgungswunsch` vom Typ `TILGUNG_AUSGESETZT` im Annuitätendarlehen-Baustein ein.

**Comment by paleise** [comment]
Danke für die Klärung. Ja, bekomme ein Kombi-Darlehen mit bestimmten Werten hin.
