### ISSUE TITLE
Errbaurecht Nein

### ISSUE THREAD

**Issue by paleise** [europace/baufismart-kundenangaben-api#79]
Es ist vielleicht nicht nötig falls kein Erbbaurecht vorhanden dieses auch auf Nein zu setzen, aber schön wäre es. Scheinbar gibt es in der UI ein weiterer Status für Erbbaurecht neben Ja/Nein.
Genauso bei Erbbaurecht "Kein" und bei Kinder "Unterhaltseinnahmen". Gebe ich das jeweilige Feld nicht mit ist nichts gewählt, gebe ich z.B. bei Kinder Unterhaltseinnahmen 0 mit, wird ist Unterhaltseinnahmen auf "Ja" gestellt. Mir fehlt jeweils die Möglichkeit die Felder auf Nein/Kein zu stellen.

**Comment by acodingsquirrel** [comment]
Hallo Peter,
wir können die Anfrage nachvollziehen. Momentan kann man das Erbbaurecht nicht auf "nein" setzten.
Wir prüfen das Anliegen jetzt intern und nehmen gegebenenfalls Anpassungen vor.

**Comment by acodingsquirrel** [comment]
Hallo Peter,

Vielen Dank, dass du uns viel Feedback zur Kundenangaben-API gegeben hast.
Basierend auf deinem Feedback und Rückfragen haben wir eine größerer Änderung vorgenommen.

Bei Angaben, bei denen eine „ja/nein“-Auswahl weitere Felder sichtbar geschaltet hat, haben wir jetzt bei allen Stellen die Option eingeführt „ja“ und „nein“ zu übermitteln.

Damit kannst du auch die von dir gewünschten Daten übertragen.
Vielen Dank für deinen Input.
