### ISSUE TITLE
Bausparvertrag als Vermögen Tarif

### ISSUE THREAD

**Issue by paleise** [europace/baufismart-kundenangaben-api#80]
Hallo,
bei vermoegen.bausparvertraege ist Feld Tarif in der Web UI ein freies Feld. Hier ein Enum. Soll das in der UI einmal geändert werden?

**Comment by s-gurevich** [comment]
Hallo Peter,

danke für den Hinweis. Bei bestehenden Bausparverträgen soll der Tarif frei erfassbar sein. Wir werden das in der API fixen und hier Bescheid geben, wenn die Anpassung online ist.

**Comment by s-gurevich** [comment]
Hallo Peter,

jetzt kannst du Freitext beim Tarif schicken. Die Anpassung in der Doku folgt gleich.
