### ISSUE TITLE
Garage vermietet

### ISSUE THREAD

**Issue by paleise** [europace/baufismart-kundenangaben-api#81]
Hallo, bei Übergabe unter finanzierungsobjekt.stellplaetze von
"stellplaetze": [
					{
						"typ": "GARAGE"
					}
				],

wird die Garage als vermietet in der UI angezeigt.

**Comment by paleise** [comment]
Konntet ihr das bereits prüfen? Mach ich da was falsch?

**Comment by paleise** [comment]
Hallo,
würde mich über eine kurze Rückinfo freuen, ob ihr das prüfen konntet. Falls dem so ist, dass Garagen immer als vermietet angelegt werden, kann ich die Version mit der neuen Schnittstelle noch nicht herausgeben.
Danke bereits für eure Mühe!

**Comment by paleise** [comment]
Leider ist das immer noch so. Ich habe die API bereits im Einsatz und muss nun die Anwender darauf hinweisen, dass nach Übertrag die Garagen/Stellplätze auf Eigengenutzt gestellt werden müssen... Ist etwas unschön...

**Comment by acodingsquirrel** [comment]
Hallo Peter,

über die Kundenangaben-API kann man an Stellen bei denen eine Auswahl "ja" oder "nein" getroffen wird und bei denen im Nachgang ein Datenfeld ausgeklappt wird kein "Nein" übertragen. Darauf hast du uns aufmerksam gemacht.

Das betrifft die Stellen:
-Erbbaurecht
-Garage
-Kinder im Haushalt
-Gewerbefläche
-weitere Staatsangehörigkeit
-Modernisierung inkl. Eigenleistung
-Kapitalbeschaffung 

Wir passen alle diese Stellen an und werden die Abwärtskompatibilität sicherstellen.
Wir sind momentan in der Umsetzung. Dabei setzen wir die Felder nacheinander um. Die Garage passen wir gerade, aktuell an.

Über die nächsten 2 Wochen werden wir alle Stellen abwärtskompatibel in die API aufgenommen haben.
Sobald die Felder umgesetzt sind, informieren wir dich hier.

**Comment by acodingsquirrel** [comment]
Hallo Peter,

Vielen Dank, dass du uns viel Feedback zur Kundenangaben-API gegeben hast.
Basierend auf deinem Feedback und Rückfragen haben wir eine größerer Änderung vorgenommen.

Bei Angaben, bei denen eine „ja/nein“-Auswahl weitere Felder sichtbar geschaltet hat, haben wir jetzt bei allen Stellen die Option eingeführt „ja“ und „nein“ zu übermitteln.

Damit kannst du auch die von dir gewünschten Daten übertragen.
Vielen Dank für deinen Input.
