### ISSUE TITLE
Response beinhaltet nur die angelegte Vorgangsnummer

### ISSUE THREAD

**Issue by paleise** [europace/baufismart-kundenangaben-api#82]
Hallo,
die KundenangabenResponse beinhaltet nur die neu angelegte Vorgangsnummer. Ich kenne keine Möglichkeit mittels dieser direkt den Fall in einem WebBrowser zu öffnen. Hier wird aus meiner Sicht immer die Teilvorgangsnummer benötigt. Kann in der Response nicht diese wie bei Bex14 mitgegeben werden oder wie muss  der Link zur Europace UI nur mit der Vorgangsnummer aussehen?
Danke bereits für eure Mühe!

Gruß Peter

**Comment by acodingsquirrel** [comment]
Hallo Peter,
springe über https://www.europace2.de/vorgang/oeffne/XXXXXX direkt in den angelegten Vorgang.
Die Kundenangaben-API liefert eine Vorgangsnummer zurück. XXXXXX steht für die Vorgangsnummer.
