### ISSUE TITLE
Ausgaben Objekt werden angelegt

### ISSUE THREAD

**Issue by paleise** [europace/baufismart-kundenangaben-api#84]
Hallo,
bei der Übergabe von
"ausgaben": {
"summePrivaterKrankenversicherungenMonatlich": 576.43
}

wird automatisch in Ausgaben "Sonstige Versicherungsausgaben", "Sonstige Ausgaben", und "Mietausgaben" generiert, zumindest werden in der Europace Web UI diesen dann angezeigt

![image](https://user-images.githubusercontent.com/28442386/110135981-71730e00-7dcf-11eb-9f5e-0dbb31b07997.png)

**Comment by s-gurevich** [comment]
Hallo Peter, danke für die Meldung! Wir haben das Verhalten gefixt. Du kannst gern nochmal testen.
