### ISSUE TITLE
Question about permission and 409

### ISSUE THREAD

**Issue by 4yourfinance** [europace/baufismart-kundenangaben-api#85]
Hello! 

We are sending new processes with client id: *775RCRM6UGPCWCMY* and *importMetadaten.betreuung.bearbeiter*: *HDY17* and got 409 errors. 

It looks like the client 775RCRM6UGPCWCMY doesn't have permission. Could you tell us please how we can check what restrictions have this client id? Or do we do something wrong? 

When we didn't use _betreuung_ we also received a successful response of 201 from the API. The process was created in the system. We just can't find it on the Europace 2 platform.

Detail about request data.

We get access token with https://api.europace.de/auth/access-token (is it right?).
When we were getting the access token we didn't set actor or subject.

We didn't set _"betreuung"_ and specify only _"tippgeber.tippgeberPartnerId"_ and sent a request to https://baufinanzierung.api.europace.de/kundenangaben.
We got the 201 response code.
A "vorgangsnummer" was assigned as "F189NC".
_("x-traceid" = "Root=1-6037cbd3-03fc589b3e763a531df113e7")_

When we set _"importMetadaten.betreuung.kundenbetreuer"_ we get *409* response code and in detail what "importMetadaten.betreuung.kundenbetreuer is not allowed"
_(Root=1-6037d0e8-0b3dbdc65ccfba673bebf9df)_

If we are trying to set "actor" or "subject" we are getting "Unauthorized client: Subject not found".

Please tell us, if we are doing something wrong.

**Comment by acodingsquirrel** [comment]
Hello 4yourfinance,
we did not respond quickly here. Is the question still relevant?
In case it is, can you share your request with us? 
For what request do you get a 409 error with client id: 775RCRM6UGPCWCMY and importMetadaten.betreuung.bearbeiter: HDY17? 
Thankyou

**Comment by acodingsquirrel** [comment]
Hello 4your finance,
can you share your request with us?
For what request do you get a 409 error with client id: 775RCRM6UGPCWCMY and importMetadaten.betreuung.bearbeiter: HDY17?
Thankyou

**Comment by acodingsquirrel** [comment]
Hallo 4your finance,

da wir nichts mehr von dir gehört haben, schließe ich das Ticket.
Melde dich gerne erneut, wenn das Thema wieder aktuell wird.
