### ISSUE TITLE
Nebenkosten

### ISSUE THREAD

**Issue by paleise** [europace/baufismart-kundenangaben-api#87]
Vielleicht müsst ihr einmal darüber diskutieren: werden keine Nebenkosten mit übergeben, werden automatisch Grunderwerbsteuer und Notargebühr vorgegeben. Ich muss also explizit die Nebenkosten mit 0 übergeben, wenn z.B. das Grundstück bereits bezahlt ist und aus welchem Grund auch immer keine Notargebühren anfallen.

**Comment by acodingsquirrel** [comment]
Hallo Peter,

in den allermeisten Fällen sind Grundstücke zum Zeitpunkt der Immobilienfinanzierung noch nicht gezahlt.
Deswegen ist das automatische Befüllen der Nebenkosten bewusst umgesetzt, um die Dateneingabe zu erleichtern. Wir erhalten dazu gutes Feedback von Beratern.
In den seltenen Fällen, in denen das Grundstück bereits bezahlt ist, muss man, genau wie in der BaufiSmart Oberfläche, dann den Automatismus korrigieren. 

Wir haben deine anderen Punkte aufbereitet und melden uns bald bei dir.

**Comment by paleise** [comment]
Danke für die Information. Ich kann gut damit leben, hab's ja bemerkt und man kann dann ja reagieren. Würde an eurer Stelle aber die Nebenkosten in der API als Pflichtfeld machen. Ist sonst aus meiner Sicht ein unschöner Seiteneffekt. Oder zumindest in der Doku angeben dass es im Hintergrund so ein Automatismus gibt.
