### ISSUE TITLE
Finanzierungsobjekt.darlehensliste

### ISSUE THREAD

**Issue by paleise** [europace/baufismart-kundenangaben-api#88]
Hallo, ich sende:
"darlehensliste": [
				{
					"@type": "BESTEHENDES_IMMOBILIENDARLEHEN",
					"grundschuldart": "BUCH_GRUNDSCHULD",
					"darlehensgeber": {
						"name": "L-Bank",
						"@type": "SONSTIGER_DARLEHENSGEBER"
					},
					"grundschuld": 17900.0,
					"darlehensbetrag": 17900.0,
					"rateMonatlich": 120.0,
					"sollzins": 6.0,
					"zinsbindungBis": "2020-05-01",
					"laufzeitende": "2025-01-01",
					"restschuld": {
						"aktuell": 6000.0
					},
					"darlehenskontonummer": "DE97660107009100017106"
				}
			]
im Finanzierungsobjekt und erhalte den Fehler:
"type":"https://api.europace.de/kundenangaben/problem/bad-request","title":"Bad Request","status":400,"detail":"Cannot deserialize into 'kundenangaben.finanzierungsobjekt.darlehensliste.[0].darlehen' at line: 1, column: 2459"

Könnte da mal jemand nachsehen, finde nicht was ich falsch mache...

Danke für die Mühe
Peter

**Comment by s-gurevich** [comment]
Hallo Peter,

bitte beachte, dass das Feld `darlehensliste` zweimal vorkommt. Im `Finanzierungsobjekt` sind die Listenelemente vom Typ `BestehendesDarlehenDesFinanzierungsobjektes`, aber in der `BestehendeImmobilie` vom Typ Ausprägung vom `BestehendesDarlehen`.
Deine Stelle ist im `Finanzierungsobjekt`. Daher müsstest du den Block mit dem bestehenden Immobiliendarlehen in das Feld `darlehen` im Typ `BestehendesDarlehenDesFinanzierungsobjektes` runter ziehen. Das sieht dann ungefähr so aus:

```
      "darlehensliste": [
        {
          "referenzId": "Referenz Abakus",
          "darlehen": {
            "@type": "BESTEHENDES_BAUSPARDARLEHEN",
            "grundschuldart": "BUCH_GRUNDSCHULD",
            "darlehensgeber": {
              "@type": "PRODUKTANBIETER_DARLEHENSGEBER",
              "produktanbieter": "ABAKUS_BANK"
            },
            "grundschuld": 501000.6,
            "darlehensbetrag": 201000.5,
            "rateMonatlich": 851.8,
            "sollzins": 4.1,
            "zinsbindungBis": "2031-01-17",
            "laufzeitende": "2036-02-22",
            "restschuld": {
              "aktuell": 151000.7,
              "zumAbloesetermin": 10100.9
            },
            "darlehenskontonummer": "DE78912345678"
          }
        }
      ]
```

**Comment by paleise** [comment]
Hallo,
jep mein Fehler... da habe ich etwas bestehendes genommen.. passt jetzt, vielen Dank!
