### ISSUE TITLE
bestehendeImmobilie PLZ

### ISSUE THREAD

**Issue by paleise** [europace/baufismart-kundenangaben-api#90]
Bei der Übergabe einer falschen PLZ wird der Vorgang nicht angelegt. Falsche PLZ beim Antragsteller geht.

"bestehendeImmobilien": [
						{
							"immobilie": {
								"adresse": {
									"strasse": "",
									"hausnummer": "",
									"plz": "3453",
									"ort": "sasdf"
								},

**Comment by acodingsquirrel** [comment]
Danke für den Hinweis.
Wir passen das Verhalten an.

**Comment by s-gurevich** [comment]
Hallo Peter, das Schicken von ungültigen PLZ führt jetzt nicht mehr zum Abbruch. Das Feld wird allerdings dann gelöscht.
