### ISSUE TITLE
Frage: Update eines bestehenden Vorgangs

### ISSUE THREAD

**Issue by D0mc3k** [europace/baufismart-kundenangaben-api#91]
Hallo Europace Team,

mit der Kundenangaben API können wir also neue Vorgänge erzeugen. Habt ihr auch geplant, dass man darüber einen bestehenden Vorgang aktualisieren (PUT Request) kann? 

Danke im Voraus

**Comment by loeffel-io** [comment]
Das würde mich auch sehr interessieren. Aktuell kann ich nur folgende Infos finden: https://docs.api.europace.de/baufinanzierung/vorgaenge/vorgang-auslesen-api/#vorgang-ver%C3%A4ndern

**Comment by acodingsquirrel** [comment]
Hallo,

das Aktualisieren von Vorgängen halten wir für eine sinnvolle Erweiterung der API.
Wir können momentan noch keinen Umsetzungszeitpunkt für die Anpassung nennen.

Wir werden gegebenenfalls auf euch zukommen, um eure Anwendungsfälle genauer zu verstehen, wenn wir mit der Umsetzung beginnen.

**Comment by StenValandt** [comment]
Hallo,
ich kann mich den Vorrednern nur anschließen. Auch ich halte die Einführung einer Vorgangs-Aktualisierungsfunktion für sehr hilfreich und sinnvoll. Der Anwendungsfall wäre für viele Nutzer eines eigenen CRM-Systems hilfreich, da bei veränderten Kunden-, und/oder Objekt- und/oder Finanzierungsangaben kein neuer Vorgang erstellt werden müsste. In der Praxis zeigt sich häufig, dass viele Vorgänge zu dem gleichen Kunden/Vorhaben erstellt werden. Die Aktualisierung müsste allerdings auch eingeschränkt werden, wenn der Vorgang in einem bestimmten Status angekommen ist. Bspw. wenn eine unterschriebene Selbstauskunft vorliegt, müsste eine Aktualisierung unterbunden werden oder der Hinweis, dass der Vorgang gesperrt ist. Eine Aktualisierungsfunktion wäre auch aus dem Grund notwendig, damit das in den Vertrieben genutzte eigene CRM auch wirklich als CRM dienen kann und nicht Europace als Teil-CRM-Lösung angesehen wird, wo nach einer Veränderung, der Vorgang neu ins eigene CRM Import werden muss. Neben der Aktualisierungsfunktion wäre auch eine Funktion zum Duplizieren und ggf. Entfernen von Duplikaten sinnvoll.
VG aus Dresden

**Comment by pscharpf** [comment]
Ja, Aktualisierungsfunktion ist zwingend. Case genau dieser wie hier beschrieben. Allerdings sollte es keine Ristriktionen für das Updaten vom Vorgang geben. Das muss jeder CRM-Anbieter nach seiner eigenen Logik speren, die API sollte aber so offen wie möglich sein für so viele Anwendungsfälle und daher keine Ristriktionen haben für irgendwelche Bearbeitungsstände.
