### ISSUE TITLE
Aufenthaltstitel NIEDERLASSUNGS_ERLAUBNIS

### ISSUE THREAD

**Issue by sklauck** [europace/baufismart-kundenangaben-api#93]
Hallo,
die Übergabe des Wertes NIEDERLASSUNGS_ERLAUBNIS im Aufenthaltstitel führt zu folgender Fehlermeldung:
"Cannot deserialize into kundenangaben.haushalte.[0].kunden.[0].personendaten.nichtEuBuerger.aufenthaltstitel: @type contains unknown type id 'NIEDERLASSUNGS_ERLAUBNIS'"
Viele Grüße

**Comment by sarahschuenemann** [comment]
Hallo, 
versuch es bitte mal ohne Unterstrich, also "NIEDERLASSUNGSERLAUBNIS".
Schöne Grüße

**Comment by sklauck** [comment]
Hallo,
danke für den Hinweis. Zur Info: Beim Auslesen der Vorgänge wird NIEDERLASSUNGS_ERLAUBNIS zurückgegeben.
Viele Grüße

**Comment by sarahschuenemann** [comment]
Hallo, 
danke für den Hinweis! Für die Kundenangaben API nutze bitte die Doku als Referenz, dann bist du auf der sicheren Seite.
Schöne Grüße
