### ISSUE TITLE
Anschlussfinanzierung, Darlehen des Finanzierungsobjekts Ablösen ja/nein #71

### ISSUE THREAD

**Issue by paleise** [europace/baufismart-kundenangaben-api#97]
Hallo zusammen, kann leider #71 nicht neu öffnen.
Ich prüfe gerade das ja/nein Problem. Bei der Anschlussfinanzierung ist das etwas anders. Beispiel: auf dem Objekt lasten zwei Darlehen. Eins soll abgelöst werden, dass andere tritt im Rang zurück. Diese Eingabemöglichkeit habe ich in der WebUI, jedoch nicht in der Schnittstelle.
Ich mach das so: die beiden Darlehen sind unter finanzierungsobjekt.darlehnsliste eingetragen. Unter finanzierungsbedarf.finanzierungszweck.abloeungDarlehenDesFinanzierungsobjektes trage ich nur die Referenz zu dem Darlehen ein, welches abgelöst werden soll. In der WebUI erscheinen dann beide Darlehen unter Vorhaben/Darlehen des Finanzierungsobjekts. So weit gut, jedoch bei dem welches nicht abgelöst werden soll ist im Feld "Ablösen?" nichts ausgewählt, also weder ja noch nein. Ich sehe keine Möglichkeit über die Schnittstelle die korrekten Werte "nein" und dann im aufgehenden Feld "Tritt im Rang zurück" "ja" einzutragen.

**Comment by acodingsquirrel** [comment]
Hallo Peter,
es stimmt, dass die Auswahl nicht übertragbar ist.
Über die Kundenangaben-API soll ein sehr großer Teil der Datenfelder übertragbar sein. 
Die Felder “Ablösen” und “Tritt im Rang zurück” sind in der Anwendung 3 Tage nach Vorgangsanlage in weniger als 1% der Fälle befüllt. Wir haben bei der Umsetzung von Datenfeldern auch die Nutzung unserer Anwendung im Blick. Wir werden das Issue mit Blick auf die geringe Feldnutzung in nächster Zeit nicht angehen.
Wenn wir feststelllen, dass "ablösen" und "tritt im Rang zurück" nach Übertrag öfter angepasst wird, dann werden wir das Thema neu bewerten.

**Comment by pscharpf** [comment]
finde das auch sehr unglücklich, wenn nach wie vor Felder nicht korrekt übergeben werden.

**Comment by acodingsquirrel** [comment]
Hallo,

in dem Kontext ist es wichtig zu sehen, dass die Kundenangaben-API wesentlich mehr Felder enthält als die vormalige BEX-API. Die Erfassung der meisten Daten ist jetzt möglich und es kann ein nahezu vollständiger Vorgang übergeben werden.

Die angesprochenen Felder werden in den ersten 3 Tagen der Beratung nahezu nicht verwendet. Wenn das Verhalten sich ändert und sich ein passender Anwendungsfall ergibt, wie ein externe Systeme das komplett ohne BaufiSmart-Frontend arbeiten, können wir die Felder immer noch anpassen. Wir werden die Relevanz des Themas laufend neu bewerten.

**Comment by StenValandt** [comment]
Hallo @acodingsquirrel , die Analyse mag Ihnen recht geben, das liegt aber daran, dass bestehende Frontend-Lösungen bisher immer nur danach gefragt haben, welche Restschuld bzw. welcher Finanzierungsbedarf grob mit der angefragten Anschlussfinanzierung besteht, um es für den User (dem Kunden) einfacher zu machen. Das erklärt auch, warum in den ersten drei Tagen bisher bestehende Darlehen keine Relevanz hatten - dies ist immer erst dann der Fall wenn es konkreter wird und der Berater den Kontakt zum Kunden aufgenommen hat. Aber es könnte auch sofort konkret werden, sodass Frontendlösungen nicht nur Zinsindikationen zeigen können. Zukünftige Lösungen u.a. eines was von uns gerade in der Umsetzung ist, sieht die Erfragung bestehender Darlehen vor und es wird auch danach gefragt, ob der Baustein abgelöst werden soll. Leider wie jetzt festgestellt wird, kann es nicht korrekt gemappt werden. Im unserem User-Frontend wird es auch eine direkte Berechnung geben, die wiederum nur korrekt funktioniert, wenn abgelöste Darlehen berücksichtigt werden können. Andernfalls würde man weiterhin in der Entwicklung stehen bleiben und nicht vorankommen. User sind heute deutlich aufgeschlossener und soweit digital affin, dass Frontend-Komplettlösungen angeboten werden können, die exakte Zielkonditionen ausspucken könnten. Ich möchte nochmal unterstreichen, dass es alles andere als irrelevant ist und es zeitnah mit korrigiert werden sollte. VG aus Dresden // fyi @tilomlr

**Comment by acodingsquirrel** [comment]
Hallo Sten,
es gibt bestehende Integrationen an Europace2, bei denen ausschließlich über externe Frontends beraten wird. 
Schicke mir doch gerne 3 bis 4 Terminvorschläge an helpdesk@europace2.de und meine Kollegen und ich setzen sich mit dir in Verbindung, um deinen Anwendungsfall zu verstehen. Wir können dir vielleicht auch einen Fingerzeig geben, wie andere Vertriebe die Anwendung umgesetzt haben.
Mich interessiert auch, ob in es bei euch um ein reines Verbraucherfrontend geht in dem auch berechnet wird und ob Verbraucher selbstständig die Entscheidung treffen bestehende Darlehen abzulösen.
