### ISSUE TITLE
Garage vermietet #81

### ISSUE THREAD

**Issue by paleise** [europace/baufismart-kundenangaben-api#98]
Hallo,
da hat die Lösung wie in #81 nicht viel gebracht. Klar, falls keine Stellplätze vorhanden kann man dies jetzt schön einstellen. Aber hier ist das eigentliche Problem, dass alle Stellplätze die übertragen werden als vermietet gekennzeichnet angelegt werden. Versucht mal so was:
				"stellplaetzeErfassung": {
					"stellplaetze": [
						{
							"typ": "STELLPLATZ"
						},
						{
							"typ": "STELLPLATZ"
						},
						{
							"typ": "CARPORT"
						},
						{
							"typ": "GARAGE"
						},
						{
							"typ": "GARAGE"
						},
						{
							"typ": "GARAGE"
						},
						{
							"typ": "TIEFGARAGEN_STELLPLATZ",
							"mieteMonatlich": 45.0
						},
						{
							"typ": "TIEFGARAGEN_STELLPLATZ",
							"mieteMonatlich": 45.0
						}
					],
					"@type": "VORHANDENE_STELLPLAETZE"

Da steht bei ALLEN Stellplätzen "Vermietet"...

Gruß
INTERCAPITAL GMBH
Peter Artelt

**Comment by acodingsquirrel** [comment]
Hallo Peter,

wir haben das Verhalten nachvollzogen.
Wir prüfen, ob wir bald in die Anpassung gehen.

Als Hintergrund, wenn du gerade am Implementieren bist: Nach 3 Tagen ist das Feld Garage in 5,9% der Fälle befüllt. Nur in 0,2% der Vorgänge ist dann etwas anderes als "vermietet" ausgewählt.
Du könntest die Implementierung also schon vornehmen, da "nicht vermietet" sehr selten vorkommt.

Wir prüfen wann wir die Anpassung vornehmen. Danke für deinen Hinweis.

**Comment by paleise** [comment]
Hallo zusammen,
naja jetzt bin ich doch etwas irritiert. Diese API soll ja die BEX ablösen. Klar wahrscheinlich aus eurer Sicht vor allem wegen OAUTH2 aber für mich war auch sehr wichtig, dass endlich fehlende Felder in der Schnittstelle ergänzt werden. Jetzt wird scheinbar geprüft, wie oft ein Feld genutzt wird... Das frustet mich schon etwas. Dachte die Tage an denen ich meinen Anwendern erklären muss dass die Übertragung nicht an unserem Programm sondern an der Schnittstelle liegt gezählt sind. Jetzt wundere ich mich nicht, warum in der Antraege API das Feld "Amtsgericht" nicht ergänzt wird. Schade.

**Comment by acodingsquirrel** [comment]
Hallo,

danke für den Hinweis. 
Wir haben die Anpassung noch einmal bewertet und das Verhalten als Fehler eingestuft. Deswegen haben wir uns entschieden eine Nachbesserung vorzunehmen.

Wir haben die API angepasst.
Bei Stellplätzen kann jetzt die Auswahl "ja" und "nein" angewählt werden. Wird "ja" angewählt, so kann auch die Miethöhe übertragen werden.
