### ISSUE TITLE
BestehendeDarlehenErfassung

### ISSUE THREAD

**Issue by paleise** [europace/baufismart-kundenangaben-api#99]
Hallo,
kann es sein, dass mit der Einführung der "Erfassung" Unterklassen "BestehendeDarlehenErfassung" nicht mehr benötigt wird?

Gruß Peter

**Comment by acodingsquirrel** [comment]
Hallo Peter,

erneut danke für den Hinweis.
Bist du hier in deiner technischen Umsetzung eingeschränkt?
Oder ist es als Hinweis an das Modell zu verstehen?

**Comment by paleise** [comment]
nur ein Hinweis
